```{r}
# 创建一些示例数据  
# set.seed(123)  
data <- data.frame(  
  group = rep(LETTERS[1:3], each = 25),  
  value = c(rnorm(25), rnorm(25, mean = 1), rnorm(25, mean = 2))  
)  
  
# 绘制箱线图  
boxplot(value ~ group, data = data,   
        main = "Boxplot of Value by Group",  
        xlab = "Group", ylab = "Value",  
        col = "lightblue", border = "orange")  
```
```{r}
library(ggplot2)  
library(dplyr)  
  

# 创建示例数组  
set.seed(123)  # 设置随机种子以便结果可复现  
A <- rnorm(1000)  # 创建示例数组A  
B_matrix <- matrix(rnorm(10*200), nrow = 200, ncol = 10)  # 创建一个10*200的数组  
  
# 创建时间序列  
time_A <- seq(1, 1000, by = 1)  
time_B <- rep(seq(1, 1000, by = 5), 10)  # 重复时间序列以匹配10组B数组  
  
# 创建数据框  
df_A <- data.frame(  
  time = time_A,  
  value = A,  
  group = "A"  
)  
  
df_B <- data.frame(  
  time = rep(time_B, 10),  
  value = as.vector(B_matrix),  
  group = rep(1:10, each = 200)  
)  
  
df <- rbind(df_A, df_B)  # 合并A和B的数据框  
  
# 使用ggplot2创建折线图，设置A和B数组的颜色  
ggplot(df, aes(x = time, y = value, color = factor(group), linetype = factor(group))) +  
  geom_line(aes(linetype = factor(group))) +  
  scale_color_manual(values = c("#000000",rep("#FFC0CB", 10))) +  
  scale_linetype_manual(values = c("solid", rep("dashed", 10)))  
```
```{r}
# 假设你的数据为 x (10*8 数组) 和 y (1*8 数组)  
y <- array(dim = K1+K2)
y[1:4] <-evalues_true$level1
y[5:8] <- evalues_true$level2
# 创建一个示例数据框  
df <- data.frame(  
  group = rep(1:8, each = 10),  # 创建组标签  
  value = c(evalue),  # 将 10*8 数组 x 转换为一个长格式的向量  
  real_value = y  # 添加真实值  
)  
  
# 使用ggplot2创建箱线图，并显示真实值  
ggplot(df, aes(x = factor(group), y = value)) +  
  geom_boxplot()  
# + geom_segment(data = subset(df, !duplicated(group)), aes(x = as.numeric(factor(group)) - 0.2, xend = as.numeric(factor(group)) + 0.2, y = real_value, yend = real_value), linetype = "dashed", color = "red")
```
