
```{r}
# data genration
I <- 100
J <- 2
L <- 20
K1 <- 4
K2 <- 4
design <- "regular"
balance <- FALSE
sigma <- 1



# create a data frame to store simulation results
nsim <- 20
sim_res <- data.frame(matrix(NA, nrow = nsim*2, ncol = 8), rep(NA,nsim*2))
colnames(sim_res) <- c("I", "J", "L", "iteration", 
                       "comptime", "MISE(Y)", "MISE(Phi)", "MISE(Psi)", "method")

```

total variance
```{r}
library(usethis)
library(devtools)
library(fields)
library(spam)
library(viridisLite)                                                                            
library(face)
require(refund)
cd4 <- Y

n <- nrow(cd4)
Tt <- ncol(cd4)
Index_A <- id_index
id <- Index_A[rep(1:nrow(Index_A), each = 20),1 ]  
t <- rep(1:T,times=n)
y <- as.vector(t(cd4))
sel <- which(is.na(y))
## organize data and apply FACEs
data <- data.frame(y=(y[-sel]),
argvals = t[-sel],
subj = id[-sel])
# data <- data[data]
# fit_face <- face.sparse(data,argvals.new=(1:T))
## set calculate.scores to TRUE if want to get scores
fit_face <- face.sparse(data,argvals.new=(1:T),calculate.scores=TRUE)
scores <- fit_face$rand_eff$scores
data.h <- data
tnew <- fit_face$argvals.new
```
```{r}
## table1: scatter plots
Xlab <- "Months since seroconversion"
Ylab <- "data"
par(mfrow=c(1,1),mar = c(4.5,4.5,3,2))
id <- data.h$subj
uid <- unique(id)
plot(data.h$argvals,data.h$y,
type = "n", 
xlab = Xlab, ylab = Ylab,
cex.lab = 1.25,cex.axis=1.25,cex.main = 1.25)
for(i in 1:10){
seq <- which(id==uid[i])
lines(data.h$argvals[seq],data.h$y[seq],lty=1,col="gray",lwd=1,type="l")
#points(data.h$argvals[seq],data.h$y[seq],col=1,lty=1,pch=1)
}
Sample <- seq(10,50,by=10)
for(i in Sample){
seq <- which(id==uid[i])
lines(data.h$argvals[seq],data.h$y[seq],lty=1,col="black",lwd=1,type="l")
}
lines(tnew,fit_face$mu.new,lwd=2,lty=2,col="red")
## table2: plots of variance/correlation functions
Cov <- fit_face$Chat.new
Cov_diag <- diag(Cov)
Cor <- fit_face$Cor.new
par(mfrow=c(1,2),mar=c(4.5,4.1,3,4.5))

plot(tnew,Cov_diag,type="l",
xlab = Xlab, ylab="",main= "test",
cex.axis=1.25,cex.lab=1.25,cex.main=1.25,lwd=2)
require(fields)
image.plot(tnew,tnew,Cor,
xlab=Xlab, ylab = Xlab,
main = "a test",
cex.axis=1.25,cex.lab=1.25,cex.main=1.25,
axis.args = list(at = c(0,0.2,0.4,0.6,0.8,1.0)),
legend.shrink=0.75,legend.line=-1.5)
```
```{r}
## pic3: prediction of several subjects
par(mfrow=c(2,2),mar=c(4.5,4.5,3,2))
Sample <- c(1,2,3,4,5)
for(i in 1:5){
sel <- which(id==uid[Sample[i]])
dati <- data.h[sel,]
seq <- 1:T
k <- length(seq)
dati_pred <- data.frame(y = rep(NA,nrow(dati) + k ),
argvals = c(rep(NA,nrow(dati)),seq),
subj=rep(dati$subj[1],nrow(dati) + k )
)
dati_pred[1:nrow(dati),] <- dati
yhat2 <- predict(fit_face,dati_pred)
data3 <- dati
Ylim <- range(c(data3$y,yhat2$y.pred))
plot(data3$argvals,data3$y,xlab=Xlab,ylab=Ylab, main = paste("Male ",i,sep=""),
cex.lab=1.25,cex.axis = 1.25,cex.main = 1.25,pch=1,xlim=c(1,T))
Ord <- nrow(dati) + 1:k

lines(dati_pred$argvals[Ord],yhat2$y.pred[Ord],col="red",lwd=2)
lines(dati_pred$argvals[Ord],
yhat2$y.pred[Ord] - 1.96*yhat2$se.pred[Ord], col="red",lwd=1,lty=2)
lines(dati_pred$argvals[Ord],
yhat2$y.pred[Ord] + 1.96*yhat2$se.pred[Ord], col="red",lwd=1,lty=2)
lines(tnew,fit_face$mu.new,lty=3,col="black",lwd=2)
legend("bottomleft",c("mean","prediction"),lty=c(3,1),col=1:2,lwd=2,bty="n")
}
## End(Not run)

```
multi 1: use sparse face directly by transformed data
```{r}
library(usethis)
library(devtools)
library(fields)
library(spam)
library(viridisLite)                                                                            
library(face)
require(refund)
library(splines)
L=100
data0 <- GeneData(I = I, J = J, L = L, design = design, sigma = sigma, balanced = balance, level = 0.5)
Y <- data0$Y
## true eigenvalues and eigenfunctions
  evalues_true <- data0$evalues 
  eigenf_true <- data0$eigenfunctions

# 使用sequence函数创建第二列，表示每个组内的元素序号  
  element_number <- sequence(table(data0$id))  
# 创建一个2xn的矩阵，第一列是分组信息，第二列是组内元素序号  
  Index_A  <- cbind(data0$id, element_number)  
 missing_rate = 0.5
  num_missing <- round(missing_rate * length(Y))  # 计算要设为缺失值的元素数量  
  missing_indices <- sample(length(Y), num_missing)  # 随机选择要设为缺失值的元素索引  
  Y[missing_indices] <- NA  # 将选定的元素设为缺失值  

  
n <- nrow(Y)
Tt <- ncol(Y)
id <- Index_A[rep(1:nrow(Index_A), each = L),1 ]  
t <- rep(1:L,times=n)
y <- as.vector(t(Y))
sel <- which(is.na(y))
## organize data and apply FACEs
data <- data.frame(y=(y[-sel]),
argvals = t[-sel],
subj = id[-sel])
# data <- data[data]
# fit_face <- face.sparse(data,argvals.new=(1:T))
## set calculate.scores to TRUE if want to get scores
ptm <- proc.time()
fit_face <- face.sparse(data,argvals.new=(1:L),calculate.scores=TRUE)
time_fast <- proc.time() - ptm
scores <- fit_face$rand_eff$scores
data.h <- data
tnew <- fit_face$argvals.new
```
```{r}
# MISE of observations
  # diff1 <- 0
  num <- sum(!is.na(Y)) 
  # for(i in 1:nrow(Y)){
  #   idx = which(!is.na(Y[i, ]))
  #   num = num + length(idx)
  #   diff1 = diff1 + sum(abs(fit_face$y.pred-Y[i,idx])^2)
  # }
  diff1 <- sum(abs(fit_face$y.pred-data$y)^2)
  MISE1_Y <- diff1/num

##### within subject calculation####
# 初始化一个空的结果数组  
mean_sub <- matrix(0,nrow=length(unique(Index_A[,2])),ncol=T)  
  
# 对数组A按照数组B中的值进行分组平均  
B <- Index_A[,2]
for (i in unique(Index_A[,2])) {  
  temp <- matrix(Y[B==i], ncol = T, byrow = TRUE)  
  mean_sub[i,] <- colMeans(temp,na.rm=TRUE)
    # mean(A[,na.rm = TRUE)  
}  

Y_2 <- matrix(0,nrow(Y),L)

for (i in 1:nrow(Y)) {
  Y_2[i,] <- Y[i,] - mean_sub[B[i],]
}


# n <- nrow(cd4)
# Tt <- ncol(cd4)
# id <- Index_A[rep(1:nrow(Index_A), each = 20),1 ]  
# t <- rep(1:T,times=n)
y2 <- as.vector(t(Y_2))
# sel <- which(is.na(y))
## organize data and apply FACEs
data <- data.frame(y=(y2[-sel]),
argvals = t[-sel],
subj = id[-sel])
# data <- data[data]

ptm <- proc.time()
fit_face_w <- face.sparse(data,argvals.new=(1:L),calculate.scores = TRUE)
time_fast <- proc.time() - ptm
# B_sp <- spline.des(knots =seq(0,T+1,length.out=7) , x = 1:T, ord = 2, outer.ok = TRUE,sparse = TRUE)$design
Theta_t = fit_face$Theta
Theta_w = fit_face_w$Theta
Theta_b = Theta_t-Theta_w
ef_t = fit_face$eigenfunctions
ef_w = fit_face_w$eigenfunctions
ef_b = ef_w[,1:4]%*% (solve(eigen(Theta_w)$vectors)%*%eigen(Theta_t-Theta_w)$vectors)[1:4,1:4]

# print(paste0("theta:",Theta_b))
# print(paste0("ef:",ef_b))
# print(Theta_b)
# print(ef_b)

  diff1 <- sum(abs(fit_face_w$y.pred-data$y)^2)
  MISE1_Y <- diff1/num
    # MISE of eigenfucntions
  MISE1_eigen1 <- sum(unlist(lapply(1:K1, function(x){
    min(sum((eigenf_true[[1]][,x]-ef_b)^2),
        sum((eigenf_true[[1]][,x]+ef_b)^2))})))/(K1*L)
  
  MISE1_eigen2 <- sum(unlist(lapply(1:K2, function(x){
    min(sum((eigenf_true[[2]][,x]-fit_face_w$eigenfunctions[,x])^2),
        sum((eigenf_true[[2]][,x]+fit_face_w$eigenfunctions[,x])^2))})))/(K2*L)
  
  ind <- 1
  sim_res[ind,1:8] <- round(c(I, J, L, iter, time_fast[3], MISE1_Y, MISE1_eigen1, MISE1_eigen2),4)
  sim_res[ind,9] <- "mfpca.face (visit)"

```
summary
```{r}
sim_res_lite <- sim_res %>% 
  group_by(I, J, L, method) %>% 
  summarise(comptime = median(comptime), `MISE(Y)` = median(`MISE(Y)`),
            `MISE(Phi)` = median(`MISE(Phi)`), `MISE(Psi)` = median(`MISE(Psi)`),.groups = "drop")
sim_res_lite

```

score estimation not use
```{r}
 print("Estimate principal component scores")
  # Xhat <- Xhat.subject <- matrix(0, nrow(df$Y), L)
  phi1 <- ef_w
  phi2 <- ef_b
  sigm2 <- fit_face_w$sigma2
    npc <- list(level1 = length(eigen(Theta_w)$values), level2 = length(eigen(Theta_t)$values))
  score1 <- matrix(0, 5, npc[[1]])
  score2 <- matrix(0, 20, npc[[2]])
  unVisits <- unique(nVisits$numVisits) 
  if (length(unVisits) < I) {
    for (j in 1:length(unVisits)) {
      Jm <- unVisits[j]
      if (sigma2 < 1e-04) {
        A <- Jm * (t(phi1) %*% phi1)
        B <- matrix(rep(t(phi1) %*% phi2, Jm), nrow = npc[[1]])
        temp <- ginv(t(phi2) %*% phi2)
      }
      else {
        if (length(evalues[[1]]) == 1) {
          A <- Jm * (t(phi1) %*% phi1)/sigma2 + 1/evalues[[1]]
        }
        else {
          A <- Jm * (t(phi1) %*% phi1)/sigma2 + diag(1/evalues[[1]])
        }
        B = matrix(rep(t(phi1) %*% phi2/sigma2, Jm), 
          nrow = npc[[1]])
        if (length(evalues[[2]]) == 1) {
          temp = ginv(t(phi2) %*% phi2/sigma2 + 1/evalues[[2]])
        }
        else {
          temp = ginv(t(phi2) %*% phi2/sigma2 + diag(1/evalues[[2]]))
        }
      }
      C <- t(B)
      invD <- kronecker(diag(1, Jm), temp)
      MatE <- ginv(A - B %*% invD %*% C)
      MatF <- -invD %*% C %*% MatE
      MatG <- -MatE %*% B %*% invD
      MatH <- invD - invD %*% C %*% MatG
      Mat1 <- cbind(MatE, MatG)
      Mat2 <- cbind(MatF, MatH)
      ind.Jm <- nVisits$id[which(nVisits$numVisits == 
        Jm)]
      YJm <- matrix(df$Ytilde[which(df$id %in% ind.Jm), 
        ], ncol = L)
      int1 <- rowsum(df$Ytilde[which(df$id %in% ind.Jm), 
        ] %*% phi1, rep(1:length(ind.Jm), each = Jm))
      int2 <- t(matrix(t(df$Ytilde[which(df$id %in% ind.Jm), 
        ] %*% phi2), nrow = npc[[2]] * Jm))
      int <- cbind(int1, int2)
      if (sigma2 >= 1e-04) {
        int <- int/sigma2
      }
      score1[which(nVisits$id %in% ind.Jm), ] <- int %*% 
        t(Mat1)
      score2[which(df$id %in% ind.Jm), ] <- t(matrix(Mat2 %*% 
        t(int), nrow = npc[[2]]))
      temp <- score1[which(nVisits$id %in% ind.Jm), ] %*% 
        t(phi1)
      # Xhat.subject[which(df$id %in% ind.Jm), ] <- temp[rep(1:length(ind.Jm), 
      #   each = Jm), ]
      # Xhat[which(df$id %in% ind.Jm), ] <- Xhat.subject[which(df$id %in% 
      #   ind.Jm), ] + score2[which(df$id %in% ind.Jm), 
        # ] %*% t(phi2)
    }
    for (g in 1:length(levels(df$visit))) {
      ind.visit <- which(df$visit == levels(df$visit)[g])
      # Xhat.subject[ind.visit, ] <- t(t(Xhat.subject[ind.visit, 
      #   ]) + mu + eta[, levels(df$visit)[g]])
      # Xhat[ind.visit, ] <- t(t(Xhat[ind.visit, ]) + mu + 
      #   eta[, levels(df$visit)[g]])
    }
    rm(YJm, g, ind.visit, ind.Jm)
  }
  # else {
  #   for (m in 1:I) {
  #     Jm <- nVisits[m, 2]
  #     if (sigma2 < 1e-04) {
  #       A <- Jm * (t(phi1) %*% phi1)
  #       B <- matrix(rep(t(phi1) %*% phi2, Jm), nrow = npc[[1]])
  #       temp <- ginv(t(phi2) %*% phi2)
  #     }
  #     else {
  #       if (length(evalues[[1]]) == 1) {
  #         A <- Jm * (t(phi1) %*% phi1)/sigma2 + 1/evalues[[1]]
  #       }
  #       else {
  #         A <- Jm * (t(phi1) %*% phi1)/sigma2 + diag(1/evalues[[1]])
  #       }
  #       B = matrix(rep(t(phi1) %*% phi2/sigma2, Jm), 
  #         nrow = npc[[1]])
  #       if (length(evalues[[2]]) == 1) {
  #         temp = ginv(t(phi2) %*% phi2/sigma2 + 1/evalues[[2]])
  #       }
  #       else {
  #         temp = ginv(t(phi2) %*% phi2/sigma2 + diag(1/evalues[[2]]))
  #       }
  #     }
  #     C <- t(B)
  #     invD <- kronecker(diag(1, Jm), temp)
  #     MatE <- ginv(A - B %*% invD %*% C)
  #     MatF <- -invD %*% C %*% MatE
  #     MatG <- -MatE %*% B %*% invD
  #     MatH <- invD - invD %*% C %*% MatG
  #     Mat1 <- cbind(MatE, MatG)
  #     Mat2 <- cbind(MatF, MatH)
  #     int1 <- colSums(matrix(df$Ytilde[df$id == ID[m], 
  #       ], ncol = L) %*% phi1)
  #     int2 <- matrix(df$Ytilde[df$id == ID[m], ], ncol = L) %*% 
  #       phi2
  #     if (sigma2 < 1e-04) {
  #       int <- c(int1, as.vector(t(int2)))
  #     }
  #     else {
  #       int <- c(int1, as.vector(t(int2)))/sigma2
  #     }
  #     score1[m, ] <- Mat1 %*% int
  #     score2[which(df$id == ID[m]), ] <- matrix(Mat2 %*% 
  #       int, ncol = npc[[2]], byrow = TRUE)
  #     for (j in which(df$id == ID[m])) {
  #       Xhat.subject[j, ] <- as.matrix(mu) + eta[, df$visit[j]] + 
  #         as.vector(phi1 %*% score1[m, ])
  #       Xhat[j, ] <- Xhat.subject[j, ] + as.vector(phi2 %*% 
  #         score2[j, ])
  #     }
  #   }
  # }
  scores <- list(level1 = score1, level2 = score2)
```

```{r}
# 导入包  
library(splines)  
library(mgcv)  
library(MASS)  
library(Matrix)  
  
# 现在你可以使用这些包中的函数了，无需单独导入函数  
# pspline.setting.mfpca <- function(x,knots,p=3,m=2,weight=NULL,type="full",
#                                     knots.option="equally-spaced"){
x=4:18 
knots = 0:T+1
p=3
m=2
weight=NULL
type="full"
knots.option="equally-spaced"
    # design matrix 
    K = length(knots)-2*p-1
    B = spline.des(knots=knots, x=x, ord=p+1, outer.ok = TRUE)$design
    # B <- splineDesign(knots, x, outer.ok = TRUE)
    bs = "ps"
    if(knots.option == "quantile"){
      bs = "bs"
    }
    s.object = s(x=x, bs=bs, k=K+p, m=c(p-1,2), sp=NULL)
    object  = smooth.construct(s.object,data = data.frame(x=x),knots=list(x=knots))
    P =  object$S[[1]]
    
    if(knots.option == "quantile") P = P / max(abs(P))*10 # rescaling
    
    if(is.null(weight)) weight <- rep(1,length(x))
    
    if(type=="full"){
      Sig = crossprod(matrix.multiply.mfpca(B,weight,option=2),B)
      eSig = eigen(Sig)
      V = eSig$vectors
      E = eSig$values
      if(min(E)<=0.0000001) {
        E <- E + 0.000001;
      }
      Sigi_sqrt = matrix.multiply.mfpca(V,1/sqrt(E))%*%t(V)
      tUPU = Sigi_sqrt%*%(P%*%Sigi_sqrt)
      Esig = eigen(tUPU,symmetric=TRUE)
      U = Esig$vectors
      s = Esig$values
      s[(K+p-m+1):(K+p)]=0
      A = B%*%(Sigi_sqrt%*%U)
    }
    
    if(type=="simple"){
      A = NULL
      s = NULL
      Sigi_sqrt = NULL
      U = NULL
    }
    
    List = list("A" = A, "B" = B, "s" = s, "Sigi.sqrt" = Sigi_sqrt, "U" = U, "P" = P)
    return(List)
}

# List <- pspline.setting.mfpca(1:T, knots=35, p=3, m=2)
```

multi2: block data --total dense FACE(not use)
```{r}
A_block <- matrix(apply(matrix(A, ncol=2), 1, mean,na.rm=TRUE), nrow = N)   
# results <- fpca.face(A_block,center = TRUE, argvals=1:10,knots=3,pve=0.99)
results <- mfpca.face(A_block,Index_A[,1],knots = 6)
# temp <- results$

##prediction
A_hat <- matrix(0,N,T/2)
score_1 = results$scores$level1
score_2 = results$scores$level2
ef_1 = results$efunctions$level1
ef_2 = results$efunctions$level2
for (i in 1:N) {
  A_hat[i,] = score_1[Index_A[i,1],]%*%t(ef_1)+score_2[i,]%*%t(ef_2)
}
mean((A_hat-A_block)^2,na.rm=TRUE)
print(ef_2)
print(results$evalues$level2)
```
```{r}

################################################################################
# I: the number of subjects.
# J: the mean number of visits for each subject.
# L: the number of observations in each curve.
# design: generate regular or irregular spaced data, default as "regular". 
# level: the level of sparse
# sigma: the standard deviation of random errors
# balanced: indicate whether to generate balanced data
################################################################################
GeneData <- function(I = 100, J = 3, L = 100, design = "regular", level = 0.1, 
                     sigma = 1, balanced = FALSE){
  
  K1 <- 4
  K2 <- 4
  K <- K1 + K2
  lambda1 <- 0.5^(0:(K1-1))
  lambda2 <- 0.5^(0:(K2-1))
  tlength <- 1
  t <- seq(0, tlength, length = L)
  tt <- t/tlength
  
  # Eigenfunctions
  f1 <- matrix(0, nrow=K1, ncol=L)
  for ( i in 1:(K1/2) ) {
    f1[2*i-1,] <- sqrt(2/tlength)*sin(i*tt*2*pi)
    f1[2*i,] <- sqrt(2/tlength)*cos(i*tt*2*pi)
  }

  f2 <- matrix(0, nrow=K2, ncol=L)
  f2[1,] <- rep(1, L)*sqrt(1/tlength)
  f2[2,] <- sqrt(3/tlength) * (2*tt - 1)
  f2[3,] <- sqrt(5/tlength) * (6*tt^2 - 6 * tt + 1)
  f2[4,] <- sqrt(7/tlength) * (20*tt^3 - 30*tt^2 + 12 * tt -1)

  # Generate scores
  ## generate number of visits for each subject from poisson distribution
  if(balanced == FALSE){
    J_subj <- pmax(rpois(I, J), 1)
  }else{
    J_subj <- rep(J, I)
  }
  n <- sum(J_subj)
  si1 <- matrix(0, nrow=I, ncol=K1)
  si2 <- matrix(0, nrow=n, ncol=K2)
  for(k in 1:K1) {
    si1[,k] <- rnorm(I, sd=sqrt(lambda1[k]))
  }
  for(k in 1:K2) {
    si2[,k] <- rnorm(n, sd=sqrt(lambda2[k]))
  }
  # Generate errors
  epsilon <- matrix(rnorm(n*L,sd=sigma),nc=L)
  
  
  # Generate dense data
  Y0 <- matrix(0,nrow=n,ncol=L)
  J_ind <- c(0, cumsum(J_subj))
  for(m in 1:I) {
    temp <- apply( ( si1[m,] %*% t(rep(1,L)) ) * f1, 2,sum)
    for(j in 1:J_subj[m]) {
      Y0[J_ind[m]+j ,] <- temp + apply( ( si2[J_ind[m]+j ,] %*% t(rep(1,L)) ) * f2, 2,sum) + epsilon[J_ind[m]+j,]
    }
  }
  
  # Generate sparse data
  if (design == "regular") {
    Y <- Y0
  } else {
    nobs <- floor(level*L)
    Y <- matrix(NA,nrow=n,ncol=L)
    for (i in 1:n) {
      idx <- sample(1:L, nobs)
      Y[i,idx] <- Y0[i,idx]
    }
  }
  
  # return values
  evalues <- list(level1=lambda1, level2=lambda2)
  eigenfunctions <- list(level1=t(f1), level2=t(f2))
  id <- rep(1:I, J_subj)
  
  return(list(Y = Y, evalues = evalues, eigenfunctions = eigenfunctions, id = id))
}


```
