preparation and data generation
```{r}
## Example of fast MFPCA on simulated data, weighted by visit or subject
## The "mfpca.face()" function is now in the refund package
 
rm(list=ls())

# load packages
library(refund)
library(MASS)
library(Matrix)
library(mgcv)
library(splines)
library(rARPACK)
library(dplyr)
# setwd("./code")
setwd("~/Desktop/functional data analysis/R package")
source("./code/GeneData.R")

## the mfpca.face() function below is now in refund
## we load the script here just for demonstration purposes
source("./code/mfpca.face.R")
source("./code/face.Cov.mfpca.R") # a supplementary function, also in refund


# set parameters
I <- 100
J <- 2
L <- 1000
K1 <- 4
K2 <- 4
design <- "regular"
balance <- FALSE
sigma <- 0.1


# create a data frame to store simulation results
nsim <- 5
sim_res <- data.frame(matrix(NA, nrow = nsim*2, ncol = 8), rep(NA,nsim*2))
colnames(sim_res) <- c("I", "J", "L", "iteration", 
                       "comptime", "MISE(Y)", "MISE(Phi)", "MISE(Psi)", "method")

```
# start simulation
method 1
```{r}
ind <- 1
nsim <- 1
for(iter in 1:nsim){
set.seed(iter)
  data <- GeneData(I = I, J = J, L = L, design = design, sigma = sigma, balanced = balance, level = 0.5)
  Y <- data$Y
 
# 使用sequence函数创建第二列，表示每个组内的元素序号  
  element_number <- sequence(table(data$id))  
# 创建一个2xn的矩阵，第一列是分组信息，第二列是组内元素序号  
  id_index  <- cbind(data$id, element_number)  
  
  missing_rate = 0.5
  num_missing <- round(missing_rate * length(Y))  # 计算要设为缺失值的元素数量  
  missing_indices <- sample(length(Y), num_missing)  # 随机选择要设为缺失值的元素索引  
  Y[missing_indices] <- NA  # 将选定的元素设为缺失值  
  nitem = 5
  Y_block =  matrix(nrow = nrow(Y),ncol = ncol(Y)/nitem)
  for (irow in 1:nrow(Y)) {
    Y_block[irow,] <-apply(matrix(Y[irow,], ncol=5,byrow = TRUE),1, mean,na.rm=TRUE)
  }
  # Y_block <- matrix(apply(matrix(Y, ncol=5,byrow = TRUE), 1, mean,na.rm=TRUE),nrow = nrow(Y),byrow = TRUE)   
  ## true eigenvalues and eigenfunctions
  evalues_true <- data$evalues 
  eigenf_true <- data$eigenfunctions
  ## other parameters for estimation
  id <- data$id

# mfpca part
## fit fast MFPCA weighted by visit (weight = "obs")

  ptm <- proc.time()
  # fit_fast <- mfpca.face(Y = Y_block, id = id, weight = "obs" ,knots =35)
  fit_fast <- mfpca.face(Y = Y_block, id = id, weight = "obs" )
  time_fast <- proc.time() - ptm
  # MISE of observations
  diff1 <- 0
  num <- 0
  for(i in 1:nrow(Y_block)){
    idx = which(!is.na(Y_block[i, ]))
    num = num + length(idx)
    diff1 = diff1 + sum(abs(fit_fast$Xhat[i,idx]-Y_block[i,idx])^2)
  }
  MISE1_Y <- diff1/num
  # MISE of eigenfucntions
  # MISE1_eigen1 <- sum(unlist(lapply(1:K1, function(x){
  #   min(sum((eigenf_true[[1]][,x]-fit_fast$efunctions[[1]][,x])^2),
  #       sum((eigenf_true[[1]][,x]+fit_fast$efunctions[[1]][,x])^2))})))/(K1*L)
  # MISE1_eigen2 <- sum(unlist(lapply(1:K2, function(x){
  #   min(sum((eigenf_true[[2]][,x]-fit_fast$efunctions[[2]][,x])^2),
  #       sum((eigenf_true[[2]][,x]+fit_fast$efunctions[[2]][,x])^2))})))/(K2*L)
  MISE1_eigen1 <- NA
  MISE1_eigen2 <- NA
  sim_res[ind,1:8] <- round(c(I, J, L, iter, time_fast[3], MISE1_Y, MISE1_eigen1, MISE1_eigen2),4)
  sim_res[ind,9] <- "mfpca.face (visit)"
  ind <- ind + 1

  ## fit fast MFPCA weighted by subject (weight = "subj")

  ptm <- proc.time()
  fit_fast2 <- mfpca.face(Y = Y_block, id = id, weight = "subj")
  time_fast2 <- proc.time() - ptm
  # MISE of observations
  diff2 <- 0
  num <- 0
  for(i in 1:nrow(Y_block)){
    idx <- which(!is.na(Y_block[i, ]))
    num <- num + length(idx)
    diff2 <- diff2 + sum(abs(fit_fast2$Xhat[i,idx]-Y_block[i,idx])^2)
  }
  MISE2_Y <- diff2/num
  
  MISE2_eigen1 <- NA
  MISE2_eigen2 <- NA
  # MISE of eigenfucntions
  # MISE2_eigen1 <- sum(unlist(lapply(1:K1, function(x){
  #   min(sum((eigenf_true[[1]][,x]-fit_fast2$efunctions[[1]][,x])^2),
  #       sum((eigenf_true[[1]][,x]+fit_fast2$efunctions[[1]][,x])^2))})))/(K1*L)
  # MISE2_eigen2 <- sum(unlist(lapply(1:K2, function(x){
  #   min(sum((eigenf_true[[2]][,x]-fit_fast2$efunctions[[2]][,x])^2),
  #       sum((eigenf_true[[2]][,x]+fit_fast2$efunctions[[2]][,x])^2))})))/(K2*L)
  sim_res[ind,1:8] <- round(c(I, J, L, iter, time_fast2[3], MISE2_Y, MISE2_eigen1, MISE2_eigen2),4)
  sim_res[ind,9] <- "mfpca.face (subject)"
  ind <- ind + 1
  
  print(iter)
  
}
```
plotting for method1 
```{r}
## table1: scatter plots
Xlab <- "Months since seroconversion"
Ylab <- "data"
par(mfrow=c(1,1),mar = c(4.5,4.5,3,2))
# id <- data.h$subj
id <- data$id
uid <- unique(id)
plot(data.h$argvals,data.h$y,
type = "n", 
xlab = Xlab, ylab = Ylab,
cex.lab = 1.25,cex.axis=1.25,cex.main = 1.25)
for(i in 1:10){
seq <- which(id==uid[i])
lines(data.h$argvals[seq],data.h$y[seq],lty=1,col="gray",lwd=1,type="l")
#points(data.h$argvals[seq],data.h$y[seq],col=1,lty=1,pch=1)
}
Sample <- seq(10,50,by=10)
for(i in Sample){
seq <- which(id==uid[i])
lines(data.h$argvals[seq],data.h$y[seq],lty=1,col="black",lwd=1,type="l")
}
lines(tnew,fit_face$mu.new,lwd=2,lty=2,col="red")
```

```{r}
## table2: plots of variance/correlation functions
Cov <- fit_face$Chat.new
Cov_diag <- diag(Cov)
Cor <- fit_face$Cor.new
par(mfrow=c(1,2),mar=c(4.5,4.1,3,4.5))

plot(tnew,Cov_diag,type="l",
xlab = Xlab, ylab="",main= "test",
cex.axis=1.25,cex.lab=1.25,cex.main=1.25,lwd=2)
require(fields)
image.plot(tnew,tnew,Cor,
xlab=Xlab, ylab = Xlab,
main = "a test",
cex.axis=1.25,cex.lab=1.25,cex.main=1.25,
axis.args = list(at = c(0,0.2,0.4,0.6,0.8,1.0)),
legend.shrink=0.75,legend.line=-1.5)
```
# summarise the results of nsim iterations
```{r}
sim_res_lite <- sim_res %>% 
  group_by(I, J, L, method) %>% 
  summarise(comptime = median(comptime), `MISE(Y)` = median(`MISE(Y)`),
            `MISE(Phi)` = median(`MISE(Phi)`), `MISE(Psi)` = median(`MISE(Psi)`),.groups = "drop")
sim_res_lite

```